spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
    username: sa
    password:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY:default-key}

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus